### ISSUE TITLE
接入socket问题

### ISSUE THREAD

**Issue by wuyiifan** [ykfe/ssr#124]
## 详细描述你的问题
按照[`mindway文档`](https://midwayjs.org/ws.html#%E6%8F%90%E4%BE%9B-socket-%E6%9C%8D%E5%8A%A1)添加`socket`服务一直报错

```json
{"message":"Converting circular structure to JSON\n    --> starting at object with constructor 'ClientRequest'\n    |     property 'socket' -> object with constructor 'Socket'\n    --- property '_httpMessage' closes the circle","stack":"TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'ClientRequest'\n    |     property 'socket' -> object with constructor 'Socket'\n    --- property '_httpMessage' closes the circle\n    at JSON.stringify (<anonymous>)\n    at respond (/Users/tiger/Documents/my-links/node_modules/koa/lib/application.js:279:15)\n    at handleResponse (/Users/tiger/Documents/my-links/node_modules/koa/lib/application.js:166:34)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","name":"TypeError","status":500}
```

也添加了启动文件`bootstrap.js`

```js
const WebFramework = require('@midwayjs/koa').Framework
const SocketFramework = require('@midwayjs/ws').Framework
const { Bootstrap } = require('@midwayjs/bootstrap')

// 加载主 web 框架
const webFramework = new WebFramework().configure({ port: 8000 })

// 加载副 ws 框架，自动适配主框架，这里不需要配置 port
const socketFramework = new SocketFramework().configure({})

Bootstrap
  .load(webFramework)
  .load(socketFramework)
  .run()
```

`src/socket/modal.ts`

```ts
import { WSController, Provide, OnWSConnection, OnWSMessage, Inject, WSEmit } from '@midwayjs/decorator'
import { Context } from '@midwayjs/socketio'

@Provide()
@WSController()
export class HelloSocketController {
  @Inject()
  ctx: Context

  @OnWSMessage('loginModal')
  @WSEmit('loginModalResult', 'modal')
  async gotMessage () {
    return 'hello world' // 这里将 hello world 字符串返回给客户端
  }

  @OnWSConnection()
  async onConnectionMethod () {
    console.log('on client connect', this.ctx.id)
  }
}
```

`package.json`

```js
"scripts": {
     ///
    "start": "ssr start --entryFile=./src/bootstrap.js",
  }
```
## 期望的结果

能正常使用`socket`服务

能在文档上补充一下demo也是很好的
## 当前使用的版本

`不要贴 package.json 用 yarn list "ssr*" ` 来查看版本。同时建议熟读[semver](https://semver.org/) 规则并且知道怎么安装最新依赖！

## 复现仓库地址

超过一行代码能描述的问题必须提供复现地址, 用默认的 `example` 给最简单的复现代码不要给包含着一堆业务代码的仓库

**Comment by zhangyuang** [comment]
midway/egg的问题去它们那里找答案。and你这里web框架应该是midway/web
