### ISSUE TITLE
npm run deploy 报错 TypeError: Cannot read properties of undefined (reading 'salt')

### ISSUE THREAD

**Issue by yijie8** [ykfe/ssr#200]
win10系统
下的最新模板 midway vue3 ssr
yarn 安装的依赖
npm start 没有问题
npm run deploy 报错

```
Package artifact...
 - Artifact file code.zip
 - Zip size 60.71MB




Error! You can try adding the -V parameter for more information output.




TypeError: Cannot read properties of undefined (reading 'salt')
    at Object.decrypt (J:\www\vue3\midway-vue3-ssr\node_modules\_crypto-js@4.1.1@crypto-js\cipher-core.js:876:102)     
    at Object.decrypt (J:\www\vue3\midway-vue3-ssr\node_modules\_crypto-js@4.1.1@crypto-js\cipher-core.js:205:59)      
    at AliyunFCPlugin.deployUseServerlessDev (J:\www\vue3\midway-vue3-ssr\node_modules\_@midwayjs_fcli-plugin-fc@1.3.4@@midwayjs\fcli-plugin-fc\src\index.ts:206:29)
    at CommandCore.execLifecycle (J:\www\vue3\midway-vue3-ssr\node_modules\_@midwayjs_command-core@1.3.4@@midwayjs\command-core\src\core.ts:216:11)
    at CommandCore.invoke (J:\www\vue3\midway-vue3-ssr\node_modules\_@midwayjs_command-core@1.3.4@@midwayjs\command-core\src\core.ts:182:5)
    at CLI.start (J:\www\vue3\midway-vue3-ssr\node_modules\_@midwayjs_command-core@1.3.4@@midwayjs\command-core\src\cli.ts:192:5)
终端进程“C:\WINDOWS\System32\cmd.exe /d /c npm run deploy”已终止，退出代码: 1。

```

**Comment by yijie8** [comment]
我下载 midway 官方模板程序
npm run deploy 没有任何问题

**Comment by zhangyuang** [comment]
提供可复现仓库

**Comment by yijie8** [comment]
请认真审题

就是你们 example 里的程序，没改任何东西。
