### ISSUE TITLE
node v18 下报错

### ISSUE THREAD

**Issue by desonyuan** [ykfe/ssr#269]
node 18 下 webpack和vite 都无法使用

**Comment by zhangyuang** [comment]
贴出错误提示。

`crypto.createHash('md4') is not supported when node version > 16,
    Please use NODE_OPTIONS=--openssl-legacy-provider ssr start to start project
    If you are using windows please use set NODE_OPTIONS=--openssl-legacy-provider, ref https://github.com/webpack/webpack/issues/14532`

**Comment by desonyuan** [comment]
webpack下是这个提示，vite下访问页面控制台报错

**Comment by zhangyuang** [comment]
贴错误提示啊。。。

**Comment by desonyuan** [comment]
ERROR  Cannot read properties of undefined (reading 'config')




 ERROR                                                                                                                                                        12:44:59
 ERROR  Cannot read properties of undefined (reading 'config')




 ERROR                                                                                                                                                        12:44:59
 ERROR  12:44:59 [vite] Error when evaluating SSR module /web/components/rectangle/index.tsx:
TypeError: Cannot read properties of undefined (reading 'config')
    at getTailwindConfig (C:\Users\Administrator\Desktop\demo\web\node_modules\tailwindcss\lib\lib\setupTrackingContext.js:85:63)
    at C:\Users\Administrator\Desktop\demo\web\node_modules\tailwindcss\lib\lib\setupTrackingContext.js:97:92
    at C:\Users\Administrator\Desktop\demo\web\node_modules\tailwindcss\lib\processTailwindFeatures.js:46:11
    at plugins (C:\Users\Administrator\Desktop\demo\web\node_modules\tailwindcss\lib\plugin.js:38:63)
    at LazyResult.runOnRoot (C:\Users\Administrator\Desktop\demo\web\node_modules\postcss\lib\lazy-result.js:339:16)
    at LazyResult.runAsync (C:\Users\Administrator\Desktop\demo\web\node_modules\postcss\lib\lazy-result.js:393:26)
    at async compileCSS (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37463:27)
    at async TransformContext.transform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37010:55)
    at async Object.transform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:39317:30)
    at async doTransform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:50043:29)




 ERROR                                                                                                                                                        12:44:59
 ERROR  12:44:59 [vite] Error when evaluating SSR module /web/pages/index/render.tsx:
TypeError: Cannot read properties of undefined (reading 'config')
    at getTailwindConfig (C:\Users\Administrator\Desktop\demo\web\node_modules\tailwindcss\lib\lib\setupTrackingContext.js:85:63)
    at C:\Users\Administrator\Desktop\demo\web\node_modules\tailwindcss\lib\lib\setupTrackingContext.js:97:92
    at C:\Users\Administrator\Desktop\demo\web\node_modules\tailwindcss\lib\processTailwindFeatures.js:46:11
    at plugins (C:\Users\Administrator\Desktop\demo\web\node_modules\tailwindcss\lib\plugin.js:38:63)
    at LazyResult.runOnRoot (C:\Users\Administrator\Desktop\demo\web\node_modules\postcss\lib\lazy-result.js:339:16)
    at LazyResult.runAsync (C:\Users\Administrator\Desktop\demo\web\node_modules\postcss\lib\lazy-result.js:393:26)
    at async compileCSS (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37463:27)
    at async TransformContext.transform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37010:55)
    at async Object.transform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:39317:30)
    at async doTransform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:50043:29)



2023-03-02 12:44:59,905 ERROR 15716 [-/::ffff:127.0.0.1/-/1973ms GET /] TypeError: Cannot read properties of undefined (reading 'config')
    at getTailwindConfig (C:\Users\Administrator\Desktop\demo\web\node_modules\tailwindcss\lib\lib\setupTrackingContext.js:85:63)
    at C:\Users\Administrator\Desktop\demo\web\node_modules\tailwindcss\lib\lib\setupTrackingContext.js:97:92
    at C:\Users\Administrator\Desktop\demo\web\node_modules\tailwindcss\lib\processTailwindFeatures.js:46:11
    at plugins (C:\Users\Administrator\Desktop\demo\web\node_modules\tailwindcss\lib\plugin.js:38:63)
    at LazyResult.runOnRoot (C:\Users\Administrator\Desktop\demo\web\node_modules\postcss\lib\lazy-result.js:339:16)
    at LazyResult.runAsync (C:\Users\Administrator\Desktop\demo\web\node_modules\postcss\lib\lazy-result.js:393:26)
    at async compileCSS (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37463:27)
    at async TransformContext.transform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37010:55)
    at async Object.transform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:39317:30)
    at async doTransform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:50043:29) {
  plugin: 'vite:css',
  id: 'C:/Users/Administrator/Desktop/demo/web/web/components/rectangle/index.module.less',
  pluginCode: "@import '../../common.less';\n" +
    '\n' +
    '.pbbContainer {\n' +
    '\tdisplay: flex;\n' +
    '\tflex-flow: row wrap;\n' +
    '\tjustify-content: space-between;\n' +
    '\toverflow: hidden;\n' +
    '\tbox-sizing: border-box;\n' +
    '\n' +
    '\t.pbbItemContainer{\n' +
    '\t\tposition: relative;\n' +
    '\t\tdisplay: block;\n' +
    '\t\twidth: 50%;\n' +
    '\t\tpadding-right: 2px;\n' +
    '\t\tbox-sizing: border-box;\n' +
    '\t\toverflow: hidden;\n' +
    '\t\t&:nth-child(2n) {\n' +
    '\t\t\tmargin-right: -3px;\n' +
    '\t\t}\n' +
    '\t}\n' +
    '\n' +
    '\t.defaultItemBg {\n' +
    '\t\tposition: relative;\n' +
    '\t\twidth: 100%;\n' +
    '\t\theight: 1.04rem;\n' +
    '\t\tbackground-repeat: no-repeat;\n' +
    "\t\tbackground-position: '0 0';\n" +
    "    background-size: 'cover';\n" +
    '\t}\n' +
    '\t\n' +
    '}\n' +
    '.pbbDescContainer {\n' +
    '\twidth: 100%;\n' +
    '\tdisplay: flex;\n' +
    '\tflex-direction: column;\n' +
    '}\n' +
    '.pbbImg {\n' +
    '\twidth: 100%;\n' +
    '\theight: 1.04rem;\n' +
    '}\n' +
    '.pbbName {\n' +
    '\twidth: 1.7rem;\n' +
    '}'
}

**Comment by desonyuan** [comment]
taiwindcss @apply 好像也不能用
 ERROR                                                                                                                                                        12:50:35
 ERROR  @apply rule is missing block or ending semi-colon




 ERROR                                                                                                                                                        12:50:35
 ERROR  12:50:35 [vite] Error when evaluating SSR module /web/components/rectangle/index.tsx:
Error: @apply rule is missing block or ending semi-colon
    at less (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37936:33)
    at async compileCSS (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37400:34)
    at async TransformContext.transform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37010:55)
    at async Object.transform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:39317:30)
    at async doTransform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:50043:29)




 ERROR                                                                                                                                                        12:50:35  
 ERROR  12:50:35 [vite] Error when evaluating SSR module /web/pages/index/render.tsx:
Error: @apply rule is missing block or ending semi-colon
    at less (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37936:33)
    at async compileCSS (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37400:34)
    at async TransformContext.transform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37010:55)
    at async Object.transform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:39317:30)
    at async doTransform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:50043:29)



2023-03-02 12:50:35,215 ERROR 16244 [-/::ffff:127.0.0.1/-/1886ms GET /] Error: @apply rule is missing block or ending semi-colon
    at less (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37936:33)
    at async compileCSS (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37400:34)
    at async TransformContext.transform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37010:55)
    at async Object.transform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:39317:30)
    at async doTransform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:50043:29) {
  loc: {
    file: 'C:\\Users\\Administrator\\Desktop\\demo\\web\\web\\common.less',
    line: 131,
    column: 2
  },
  plugin: 'vite:css',
  id: 'C:/Users/Administrator/Desktop/demo/web/web/common.less',
  pluginCode: "@import '../../common.less';\n" +
    '\n' +
    '.pbbContainer {\n' +
    '\tdisplay: flex;\n' +
    '\tflex-flow: row wrap;\n' +
    '\tjustify-content: space-between;\n' +
    '\toverflow: hidden;\n' +
    '\tbox-sizing: border-box;\n' +
    '\n' +
    '\t.pbbItemContainer{\n' +
    '\t\tposition: relative;\n' +
    '\t\tdisplay: block;\n' +
    '\t\twidth: 50%;\n' +
    '\t\tpadding-right: 2px;\n' +
    '\t\tbox-sizing: border-box;\n' +
    '\t\toverflow: hidden;\n' +
    '\t\t&:nth-child(2n) {\n' +
    '\t\t\tmargin-right: -3px;\n' +
    '\t\t}\n' +
    '\t}\n' +
    '\n' +
    '\t.defaultItemBg {\n' +
    '\t\tposition: relative;\n' +
    '\t\twidth: 100%;\n' +
    '\t\theight: 1.04rem;\n' +
    '\t\tbackground-repeat: no-repeat;\n' +
    "\t\tbackground-position: '0 0';\n" +
    "    background-size: 'cover';\n" +
    '\t}\n' +
    '\t\n' +
    '}\n' +
    '.pbbDescContainer {\n' +
    '\twidth: 100%;\n' +
    '\tdisplay: flex;\n' +
    '\tflex-direction: column;\n' +
    '}\n' +
    '.pbbImg {\n' +
    '\twidth: 100%;\n' +
    '\theight: 1.04rem;\n' +
    '}\n' +
    '.pbbName {\n' +
    '\twidth: 1.7rem;\n' +
    '}',
  frame: '128|  \n' +
    '129|    .mouse-dot-container {\n' +
    '130|      @apply fixed top-0 left-0 will-change-transform z-50 transition-transform ease-out duration-500 w-12 h-12 scale-50 rounded-full pointer-events-none\n' + 
    '   |                                                                                                                                               ^\n' +
    '131|    }\n' +
    '132|  '
}
2023-03-02 12:50:35,220 ERROR 16244 [-/::1/-/1421ms GET /] Error: @apply rule is missing block or ending semi-colon
    at less (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37936:33)
    at async compileCSS (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37400:34)
    at async TransformContext.transform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:37010:55)
    at async Object.transform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:39317:30)
    at async doTransform (C:\Users\Administrator\Desktop\demo\web\node_modules\vite\dist\node\chunks\dep-689425f3.js:50043:29) {
  loc: {
    file: 'C:\\Users\\Administrator\\Desktop\\demo\\web\\web\\common.less',
    line: 131,
    column: 2
  },
  plugin: 'vite:css',
  id: 'C:/Users/Administrator/Desktop/demo/web/web/common.less',
  pluginCode: "@import '../../common.less';\n" +
    '\n' +
    '.pbbContainer {\n' +
    '\tdisplay: flex;\n' +
    '\tflex-flow: row wrap;\n' +
    '\tjustify-content: space-between;\n' +
    '\toverflow: hidden;\n' +
    '\theight: 1.04rem;\n' +
    '}\n' +
    '.pbbName {\n' +
    '\twidth: 1.7rem;\n' +
    '}',
  frame: '128|  \n' +
    '129|    .mouse-dot-container {\n' +
    '130|      @apply fixed top-0 left-0 will-change-transform z-50 transition-transform ease-out duration-500 w-12 h-12 scale-50 rounded-full pointer-events-none\n' + 
    '   |                                                                                                                                               ^\n' +
    '131|    }\n' +
    '132|  ',
  status: 500
}

**Comment by zhangyuang** [comment]
vite场景的问题跟node18没有任何关系，如果你要用tailwind自行去文档查找如何在vite场景下用tailwind。
webpack场景的启动问题框架已经提示你要如何启动了就是我贴出来的部分
