### ISSUE TITLE
更新了最新版本以后发布到阿里云不成功

### ISSUE THREAD

**Issue by stellacoursera** [ykfe/ssr#338]
提问前请确认以下几点信息，否则你的问题将不会被解答

- 参考 https://zhuanlan.zhihu.com/p/25795393 学会正确的提问方式
- 确定已经阅读过文档 http://doc.ssr-fc.com/ 并且文档中搜索不到相关答案
- 对应服务端框架的使用问题请去它们的官方文档找答案。例如 [Midway](https://midwayjs.org/), [Nest.js](https://nestjs.com/)
- 如果你确认当前是一个 bug 请给最简复现仓库。只有一张图或者信息不足的问题将会被直接关闭
- 原则上这里只解答与本框架有关的问题。关于其他问题例如 Node.js 怎么连 Mysql 怎么获取 cookie 这种基础问题你应该去 Google 找答案而不是在这里。

## 详细描述你的问题

更新到最新版本，发布阿里云报错。直接使用midway-react-ssr 的Demo未修改直接发布阿里云也报错，错误如下：
TypeError: The "id" argument must be of type string. Received undefined
    at Module.require (node:internal/modules/cjs/loader:1304:3)
    at require (node:internal/modules/helpers:179:18)
    at compileTypeScript (E:\Project\ssr-demo\node_modules\@midwayjs\command-core\dist\utils\compileTypeScript.js:13:16)
    at PackagePlugin.compile (E:\Project\ssr-demo\node_modules\@midwayjs\fcli-plugin-package\dist\index.js:455:88)
    at CommandCore.execLifecycle (E:\Project\ssr-demo\node_modules\@midwayjs\command-core\dist\core.js:188:21)
    at CommandCore.invoke (E:\Project\ssr-demo\node_modules\@midwayjs\command-core\dist\core.js:150:9)
    at AliyunFCPlugin.deployUseServerlessDev (E:\Project\ssr-demo\node_modules\@midwayjs\fcli-plugin-fc\dist\index.js:181:9)
    at CommandCore.execLifecycle (E:\Project\ssr-demo\node_modules\@midwayjs\command-core\dist\core.js:188:21)
    at CommandCore.invoke (E:\Project\ssr-demo\node_modules\@midwayjs\command-core\dist\core.js:150:9)
    at CLI.start (E:\Project\ssr-demo\node_modules\@midwayjs\command-core\dist\cli.js:163:9) {
  code: 'ERR_INVALID_ARG_TYPE'

## 期望的结果
正确发布

## 当前使用的版本

最新版本安装

**Comment by zhangyuang** [comment]
无法复现，试了一下没有问题。如果是安装了全局pnpm，可以尝试默认demo的pnpm-lock文件重新ssr deploy
